### ISSUE TITLE
sidebar の背景画像の長さが足りない

### ISSUE THREAD

**Issue by hsbt** [rubima/hiki-theme#1]
ref https://github.com/rubima/rubima/issues/90

**Comment by gunjisatoshi** [comment]
これはいちいち長い画像を作りなおしていると延々とサポートが必要な予感がします。
cssで繰り返し表現みたいなのってできないんでしたっけ。

**Comment by znz** [comment]
`repeat-y` で出来そうですが、繰り返す部分と繰り返さない部分が分かれている必要がありそうな気がします。
頑張れば同じ画像のままでも出来るのかもしれませんが、 CSS はあんまり詳しくないのでよくわからないです。

**Comment by znz** [comment]
元々の画像部分はソースコードが埋め込まれているということで、同じようにソースコードを埋め込んだ部分を伸ばすならまだ修正が必要ということでまだ open のままにしています。

**Comment by znz** [comment]
https://github.com/rubima/rubima/issues/218 という問題が発生しているので一部戻します。
